import { execFileSync } from "node:child_process"
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, isAbsolute, join, relative, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const output = join(root, "src", "protocol", "generated")
const expectedVersion = readFileSync(join(root, "codex-version.txt"), "utf8").trim()
const binary = process.env.CODEX_BIN || "codex"

function version(path: string) {
  const found = execFileSync(path, ["--version"], { encoding: "utf8" }).match(/\d+\.\d+\.\d+(?:-[A-Za-z0-9.]+)?/)
  if (!found) throw new Error(`Could not parse Codex version from ${path}`)
  return found[0]
}

function files(path: string, base = path): string[] {
  return readdirSync(path, { withFileTypes: true })
    .flatMap((entry) => {
      const target = join(path, entry.name)
      if (entry.isDirectory()) return files(target, base)
      if (!entry.isFile() || !entry.name.endsWith(".ts")) return []
      return [relative(base, target)]
    })
    .sort()
}

function normalize(path: string, generatedRoot: string) {
  const header = [
    "// AUTOGENERATED - do not edit.",
    "// Source: `codex app-server generate-ts --experimental`.",
    `// Generated from codex-cli ${expectedVersion}, licensed Apache-2.0.`,
    "// Regenerate: `bun run generate:protocol` from packages/codex.",
    "",
  ].join("\n")
  const source = readFileSync(join(generatedRoot, path), "utf8")
    .replace(/^\/\/ GENERATED CODE!.*\n(?:\n)?/, "")
    .replace(/(from\s+["'])(\.\.?\/[^"']+?)(["'])/g, (_match, prefix: string, specifier: string, quote: string) => {
      const absolute = resolve(dirname(join(generatedRoot, path)), specifier)
      const suffix = (() => {
        try {
          return statSync(absolute).isDirectory() ? "/index.js" : ".js"
        } catch {
          return ".js"
        }
      })()
      return `${prefix}${specifier}${suffix}${quote}`
    })
  return header + source.replace(/\r\n/g, "\n")
}

function generate() {
  const actualVersion = version(binary)
  if (actualVersion !== expectedVersion) {
    throw new Error(`Codex version mismatch: expected ${expectedVersion}, got ${actualVersion} from ${binary}`)
  }
  const generatedRoot = mkdtempSync(join(tmpdir(), "opencode-codex-protocol-"))
  try {
    execFileSync(binary, ["app-server", "generate-ts", "--out", generatedRoot, "--experimental"], {
      stdio: "inherit",
    })
    const generated = files(generatedRoot)
    if (process.argv.includes("--check")) {
      const committed = files(output)
      const mismatch = generated.find(
        (path) => readFileSync(join(output, path), "utf8") !== normalize(path, generatedRoot),
      )
      if (mismatch || generated.join("\n") !== committed.join("\n")) {
        throw new Error(`Generated Codex protocol is stale${mismatch ? ` at ${mismatch}` : ""}`)
      }
      console.log(`Codex protocol matches ${actualVersion} (${generated.length} files)`)
      return
    }
    readdirSync(output, { withFileTypes: true })
      .filter((entry) => entry.name !== "README.md")
      .forEach((entry) => rmSync(join(output, entry.name), { recursive: true, force: true }))
    generated.forEach((path) => {
      const target = join(output, path)
      mkdirSync(dirname(target), { recursive: true })
      writeFileSync(target, normalize(path, generatedRoot))
    })
    console.log(`Generated ${generated.length} protocol files from codex-cli ${actualVersion}`)
  } finally {
    rmSync(generatedRoot, { recursive: true, force: true })
  }
}

if (!isAbsolute(output)) throw new Error("Protocol output must be absolute")
generate()
